"""Add location fields to TourStop

Revision ID: 00b83d32a888
Revises: d6be98cfe7b0
Create Date: 2026-01-08 20:21:56.343537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b83d32a888'
down_revision = 'd6be98cfe7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_column('location_notes')
        batch_op.drop_column('location_country')
        batch_op.drop_column('location_city')
        batch_op.drop_column('location_address')

    # ### end Alembic commands ###
