"""Add LineupSlot model

Revision ID: 00e9f0bad5f8
Revises: r1s2c3h4e5d6
Create Date: 2026-01-21 21:20:27.806435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9f0bad5f8'
down_revision = 'r1s2c3h4e5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create lineup_slots table
    op.create_table('lineup_slots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tour_stop_id', sa.Integer(), nullable=False),
        sa.Column('performer_name', sa.String(length=100), nullable=False),
        sa.Column('performer_type', sa.Enum('main_artist', 'opening_act', 'support', 'dj_set', 'special_guest', 'other', name='performertype'), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=True),
        sa.Column('set_length_minutes', sa.Integer(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_confirmed', sa.Boolean(), nullable=False, default=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tour_stop_id'], ['tour_stops.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_slots_tour_stop_id'), 'lineup_slots', ['tour_stop_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PASSPORT', 'VISA', 'ID_CARD', 'WORK_PERMIT', 'CONTRACT', 'RIDER', 'INSURANCE', 'RIB', 'BANK_DETAILS', 'URSSAF_CERTIFICATE', 'CONGES_SPECTACLE', 'SIRET_DOCUMENT', 'TAX_DOCUMENT', 'INVOICE', 'RECEIPT', 'EXPENSE_RECEIPT', 'OTHER', name='documenttype'),
               existing_nullable=False)

    with op.batch_alter_table('tour_stop_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tour_stops', ['tour_stop_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('draft', 'pending', 'confirmed', 'performed', 'settled', 'canceled', 'rescheduled', name='tourstopstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop lineup_slots table
    op.drop_index(op.f('ix_lineup_slots_tour_stop_id'), table_name='lineup_slots')
    op.drop_table('lineup_slots')

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'pending', 'confirmed', 'performed', 'settled', 'canceled', 'rescheduled', name='tourstopstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('tour_stop_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'tour_stops', ['tour_stop_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('document_type',
               existing_type=sa.Enum('PASSPORT', 'VISA', 'ID_CARD', 'WORK_PERMIT', 'CONTRACT', 'RIDER', 'INSURANCE', 'RIB', 'BANK_DETAILS', 'URSSAF_CERTIFICATE', 'CONGES_SPECTACLE', 'SIRET_DOCUMENT', 'TAX_DOCUMENT', 'INVOICE', 'RECEIPT', 'EXPENSE_RECEIPT', 'OTHER', name='documenttype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
