"""add_health_consent_and_account_deletion_fields

Revision ID: 09eda1c0fb44
Revises: dd3299cda23c
Create Date: 2026-02-27 21:11:49.511004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09eda1c0fb44'
down_revision = 'dd3299cda23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_data_consent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('health_data_consent_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('health_data_consent_date')
        batch_op.drop_column('health_data_consent')

    # ### end Alembic commands ###
