"""Add ticket_url to tour_stops

Revision ID: 13bf6b216395
Revises: 
Create Date: 2026-01-04 16:13:35.738994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bf6b216395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_column('ticket_url')

    # ### end Alembic commands ###
