"""Add_notifications_table

Revision ID: 49d627652263
Revises: a0cf896ff6c3
Create Date: 2026-01-08 13:04:12.309887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49d627652263'
down_revision = 'a0cf896ff6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestlist_entries_guestlist_id'))
        batch_op.drop_constraint(batch_op.f('fk_guestlist_entries_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_type',
               existing_type=postgresql.ENUM('show', 'day_off', 'travel', 'studio', 'promo', 'rehearsal', 'press', 'meet_greet', 'photo_video', 'other', name='eventtype'),
               nullable=False,
               existing_server_default=sa.text("'show'::eventtype"))
        batch_op.drop_index(batch_op.f('ix_tour_stops_band_id'))
        batch_op.drop_index(batch_op.f('ix_tour_stops_tour_id'))
        batch_op.drop_index(batch_op.f('ix_tour_stops_venue_id'))
        batch_op.create_index(batch_op.f('ix_tour_stops_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_stops_event_type'))
        batch_op.create_index(batch_op.f('ix_tour_stops_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_stops_tour_id'), ['tour_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_stops_band_id'), ['band_id'], unique=False)
        batch_op.alter_column('event_type',
               existing_type=postgresql.ENUM('show', 'day_off', 'travel', 'studio', 'promo', 'rehearsal', 'press', 'meet_greet', 'photo_video', 'other', name='eventtype'),
               nullable=True,
               existing_server_default=sa.text("'show'::eventtype"))
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guestlist_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_guestlist_entries_user_id'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_guestlist_entries_guestlist_id'), ['tour_stop_id'], unique=False)

    # ### end Alembic commands ###
