"""Add location coordinates to TourStop

Revision ID: 64bf63b18108
Revises: 00b83d32a888
Create Date: 2026-01-08 20:39:30.627288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bf63b18108'
down_revision = '00b83d32a888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('location_longitude', sa.Numeric(precision=10, scale=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_column('location_longitude')
        batch_op.drop_column('location_latitude')

    # ### end Alembic commands ###
