"""Add financial module: payments, invoices, audit enhancements

Revision ID: 6bf86f0608f1
Revises: n2o4p6r8t0v2
Create Date: 2026-01-13 14:03:28.916626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf86f0608f1'
down_revision = 'n2o4p6r8t0v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('old_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_column('error_message')
        batch_op.drop_column('success')
        batch_op.drop_column('new_values')
        batch_op.drop_column('old_values')
        batch_op.drop_column('module')
        batch_op.drop_column('severity')
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_email')
        batch_op.drop_column('entity_reference')

    # ### end Alembic commands ###
