"""add venue_rental_cost to tour_stops

Revision ID: 6ea92203edbe
Revises: r0s2t4v6x8z0
Create Date: 2026-01-30 12:03:54.643796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea92203edbe'
down_revision = 'r0s2t4v6x8z0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('logistics_info', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'BOOKED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='logisticsstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('tour_stop_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tour_stop_members_tour_stop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tour_stop_members_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tour_stops', ['tour_stop_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_rental_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('reschedule_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'tour_stops', ['rescheduled_from_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'MANAGER', 'STAFF', 'VIEWER', 'EXTERNAL', name='accesslevel'),
               nullable=False,
               existing_server_default=sa.text("'STAFF'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_level',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'STAFF', 'VIEWER', 'EXTERNAL', name='accesslevel'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'STAFF'::character varying"))

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reschedule_reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('venue_rental_cost')

    with op.batch_alter_table('tour_stop_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tour_stop_members_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tour_stop_members_tour_stop_id_fkey'), 'tour_stops', ['tour_stop_id'], ['id'])

    with op.batch_alter_table('logistics_info', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'BOOKED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='logisticsstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    # ### end Alembic commands ###
