"""Add tour_stop_members association table

Revision ID: a0cf896ff6c3
Revises: h8j0l2n4p6r8
Create Date: 2026-01-07 16:21:48.132099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0cf896ff6c3'
down_revision = 'h8j0l2n4p6r8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Créer la table d'association tour_stop_members
    op.create_table('tour_stop_members',
        sa.Column('tour_stop_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tour_stop_id'], ['tour_stops.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('tour_stop_id', 'user_id')
    )
    
    with op.batch_alter_table('guestlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestlist_entries_guestlist_id'))
        batch_op.drop_constraint(batch_op.f('fk_guestlist_entries_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_type',
               existing_type=postgresql.ENUM('show', 'day_off', 'travel', 'studio', 'promo', 'rehearsal', 'press', 'meet_greet', 'photo_video', 'other', name='eventtype'),
               nullable=False,
               existing_server_default=sa.text("'show'::eventtype"))
        batch_op.drop_index(batch_op.f('ix_tour_stops_band_id'))
        batch_op.drop_index(batch_op.f('ix_tour_stops_tour_id'))
        batch_op.drop_index(batch_op.f('ix_tour_stops_venue_id'))
        batch_op.create_index(batch_op.f('ix_tour_stops_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Supprimer la table tour_stop_members
    op.drop_table('tour_stop_members')
    
    with op.batch_alter_table('tour_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_stops_event_type'))
        batch_op.create_index(batch_op.f('ix_tour_stops_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_stops_tour_id'), ['tour_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_stops_band_id'), ['band_id'], unique=False)
        batch_op.alter_column('event_type',
               existing_type=postgresql.ENUM('show', 'day_off', 'travel', 'studio', 'promo', 'rehearsal', 'press', 'meet_greet', 'photo_video', 'other', name='eventtype'),
               nullable=True,
               existing_server_default=sa.text("'show'::eventtype"))
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guestlist_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_guestlist_entries_user_id'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_guestlist_entries_guestlist_id'), ['tour_stop_id'], unique=False)

    # ### end Alembic commands ###
