"""Add crew information fields to User

Revision ID: d6be98cfe7b0
Revises: j9k1m3o5q7s9
Create Date: 2026-01-08 16:28:30.476134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6be98cfe7b0'
down_revision = 'j9k1m3o5q7s9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('passport_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passport_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('preferred_airline', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seat_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('meal_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hotel_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('dietary_restrictions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medical_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('medical_notes')
        batch_op.drop_column('allergies')
        batch_op.drop_column('dietary_restrictions')
        batch_op.drop_column('emergency_contact_email')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_relation')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('hotel_preferences')
        batch_op.drop_column('meal_preference')
        batch_op.drop_column('seat_preference')
        batch_op.drop_column('preferred_airline')
        batch_op.drop_column('passport_expiry')
        batch_op.drop_column('passport_number')
        batch_op.drop_column('nationality')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
